### ISSUE TITLE
Tables do not render correctly

### ISSUE THREAD

**Issue by tjdavis3** [stephenafamo/goldmark-pdf#1]
If the cell contents are longer than the heading length of the column then the next column will overwrite the last part of the previous column.  Column widths are determined based on the values in the header row.  Column contents do not wrap (at least not without changing the row height, which I have not tested).

This makes the table functionality not very useful except for the simplest of tables, which is a shame since otherwise the generated PDF looks very good.

**Comment by stephenafamo** [comment]
This should not happen.

I'll try this myself, but can you give a sample markdown that you know renders improperly?

**Comment by stephenafamo** [comment]
I'll try to fix as soon as I can, but I have quite a bit on my plate now so it may be slower than expected.

**Comment by tjdavis3** [comment]
Thank you for looking into it.  Here's an example .md and the corresponding pdf.

[DevReport_0611.md](https://github.com/stephenafamo/goldmark-pdf/files/6671442/DevReport_0611.md)
[rpt.pdf](https://github.com/stephenafamo/goldmark-pdf/files/6671443/rpt.pdf)

**Comment by erwin** [comment]
@stephenafamo 

Have you had a chance to get implement any table support so far? If there is some amount of table support that we can work within the parameters of, that would be good to know.

I tried adding fixed width spacing to @tjdavis3's example to see if it would work, but for me, the table was still not formatted the way I would expect in the output PDF...

```
| project                        | Status      | Due         | Stories | Completed | % Completed |
| ------------------------------ | ----------- | ----------- | ------- | --------- | ----------- |
| Document System                | in progress | 06-29-2021  |       25|         11|         44% |
| Message-based APIs             | in progress | 06-25-2021  |       11|          7|         63% |
| Inventory MVP                  | in progress | 07-01-2021  |       78|         67|         85% |
| Company Master GP Sync Service | in progress | 07-02-2021  |        6|          0|          0% |
| Data Warehouse                 | in progress | 07-04-2021  |       28|         17|         60% |
```

For some reason it's getting parsed as `text` rather than as a table. I see this in the log:

```log
-[Text] Projects Health
-[Heading (leaving)]
[Paragraph (entering)]
[... Margins (left, top, right, bottom:] 28.35 28.35 28.35 56.7
[Text] | project                        | Status      | Due         | Stories | Completed | % Completed |
[Text] | ------------------------------ | ----------- | ----------- | ------- | --------- | ----------- |
[Text] | Document System                | in progress | 06-29-2021  |       25|         11|         44% |
[Text] | Message-based APIs             | in progress | 06-25-2021  |       11|          7|         63% |
[Text] | Inventory MVP                  | in progress | 07-01-2021  |       78|         67|         85% |
[Text] | Company Master GP Sync Service | in progress | 07-02-2021  |        6|          0|          0% |
[Text] | Data Warehouse                 | in progress | 07-04-2021  |       28|         17|         60% |
[Paragraph (leaving)]
[... Margins (left, top, right, bottom:] 28.35 28.35 28.35 56.7
```


Output PDF looks like:

![image](https://user-images.githubusercontent.com/11534217/203744278-266d2e51-b47e-47cc-aa6f-8f02fb9fce44.png)

**Comment by ivanjaros** [comment]
You need to enable the goldmark extension.GFM or extension.Table. `goldmark.WithExtensions(extension.GFM)`.

**Comment by stephenafamo** [comment]
@tjdavis3 & @erwin let me know if @ivanjaros's suggestion fixed the issue or not.
