### ISSUE TITLE
how To render Unicode font，like cjk font

### ISSUE THREAD

**Issue by hh02** [stephenafamo/goldmark-pdf#20]
Chinese font are rendered as box
<img width="630" alt="image" src="https://github.com/stephenafamo/goldmark-pdf/assets/57320088/ab075cde-5eaf-4664-a286-7a44a62b7c56">

```go
	notoFont := pdf.Font{
		CanUseForText:  true,
		CanUseForCode:  false,
		Category:       "sans-serif",
		Family:         "Noto Sans SC",
		FileRegular:    "regular",
		FileItalic:     "regular",
		FileBold:       "700",
		FileBoldItalic: "700",
		Type:           pdf.FontTypeGoogle,
	}
	config := pdf.DefaultConfig()
	err := pdf.AddFonts(ctx, config.PDF, []pdf.Font{notoFont}, nil)
	if err != nil {
		return nil, err
	}
	md := goldmark.New(
		goldmark.WithRenderer(pdf.New(
			pdf.WithConfig(config),
			pdf.WithBodyFont(pdf.FontNotoSans))),
	)
	buf := bytes.Buffer{}
	if err := md.Convert([]byte(markdownStr), &buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
```

**Comment by stephenafamo** [comment]
I'm not sure, and unfortunately, I don't have the time to properly debug this.

I'll mark it as a bug. If you have the time to take a look, I'll appreciate it.

**Comment by hh02** [comment]
The reason is that fpdf does not support otf font, I download ttf, and use custom way.

**Comment by we1zhang** [comment]
@hh02 how to generate Chinese font correctly? Chinese font are rendered as box

**Comment by we1zhang** [comment]
@stephenafamo how to generate Chinese font correctly? Chinese font are rendered as box

**Comment by stephenafamo** [comment]
Try using a font that supports Chinese characters

**Comment by we1zhang** [comment]
IS there any font that supports Chinese characters ever?
@stephenafamo

**Comment by we1zhang** [comment]
there is a ttf in my local project "MicrosoftYaHeiLight-01.ttf". 
how can i use this font in pdf body?
@stephenafamo Thanks.

**Comment by we1zhang** [comment]
`      ctx := context.Background()
	msyhl := goldmarkPdf.Font{
		CanUseForText:  true,
		CanUseForCode:  false,
		Category:       "msyhl",
		Family:         "msyhl",
		FileRegular:    "regular",
		FileItalic:     "italic",
		FileBold:       "700",
		FileBoldItalic: "700italic",
		Type:           goldmarkPdf.FontTypeCustom,
	}

	fpdf := goldmarkPdf.NewFpdf(ctx, goldmarkPdf.FpdfConfig{Orientation: "P", PaperSize: "A4"}, nil)
	fpdf.Fpdf.AddUTF8Font("msyhl", "", "MicrosoftYaHeiLight-01.ttf")
	fpdf.Fpdf.AddUTF8Font("msyhl", "B", "MicrosoftYaHeiLight-01.ttf")
	fpdf.Fpdf.SetFont("msyhl", "", 12)

	renderer := goldmarkPdf.New(
		goldmarkPdf.WithTraceWriter(os.Stdout),
		goldmarkPdf.WithPDF(fpdf),
		goldmarkPdf.WithContext(ctx),
		goldmarkPdf.WithHeadingFont(msyhl),
		goldmarkPdf.WithBodyFont(msyhl),
		goldmarkPdf.WithCodeFont(goldmarkPdf.FontRobotoMono),
	)

	markdown := goldmark.New(
		goldmark.WithRenderer(
			renderer,
		),
		goldmark.WithExtensions(extension.GFM, extension.Table), // required for tables
	)

	file, err := os.Create("output.pdf")
	if err != nil {
		panic(err)
	}
	// now the actual rendering to PDF
	if err := markdown.Convert([]byte(mdsource), file); err != nil {
		log.Error(err)
		return
	}`
