### ISSUE TITLE
How to specify font size?

### ISSUE THREAD

**Issue by TLINDEN** [stephenafamo/goldmark-pdf#21]
I can change the font, but not the font size. At least the font struct does not have a size option. Is this possible?

**Comment by stephenafamo** [comment]
Set the `Styles` configuration, and use `WithConfig`.

Make sure to use `WithConfig` as the first option since it overwrites the current config.

**Comment by TLINDEN** [comment]
But for code blocks there's only `CodeFont` which is a Font, not a Style:

https://github.com/stephenafamo/goldmark-pdf/blob/aaac2858e54e6cb50122ce4e89b3dc30f8a7fef6/style.go#L45

So I could change font parameters for headings and blocks etc, but not for code.

However, there's `CodeBlockStyle`, but this isn't a `pdf.Style` but a `chroma.Style` for whatever reason. By default it's set to https://github.com/alecthomas/chroma/blob/master/styles/monokai.xml. However, chroma styles do not provide a way to specify the font size as far I can see.

**Comment by stephenafamo** [comment]
IIRC, the code will be formatted in the same size as the current context. So if you're in a heading, it will use the heading font size.

**Comment by TLINDEN** [comment]
Well, but then I'd need to decrease the font size of all text in the document. But I want only the code parts to be smaller.

**Comment by stephenafamo** [comment]
If you can send in a PR for this, I would be happy to review.

**Comment by TLINDEN** [comment]
Well, unfortunately I don't understand the code and the inner workings enough to be able to make any reasonable modifications. I especially don't understand why there are two completely different style systems being used. I tried to turn `CodeBlockStyle` into a normal `Style` but failed miserably as both style types are being used in multiple places and there's no way to convert a `Style` to `chroma.Style` (as far as I could figure).

So, I'd really appreciate an API way to modify code font size as any other font size using the goldmark-pdf module.

**Comment by stephenafamo** [comment]
Honestly, the entire package is probably due for a total rewrite.  
Unfortunately I do not have the time to dig into it to make any changes right now (or in the near future). Sorry.
