### ISSUE TITLE
How to generate a PDF file in landscape format?

### ISSUE THREAD

**Issue by TLINDEN** [stephenafamo/goldmark-pdf#22]
I have to generate PDFs with relatively wide code blocks and tables, so landscape mode would fit this much better. Is this possible somehow?

**Comment by stephenafamo** [comment]
You can set the `Orientation` in two ways

1. Use `WithFpdf` Option and set the `Orientation` accordingly
2. Use `NewFpdf` for greater control, and then pass that to the `WithPDF` option.

**Comment by TLINDEN** [comment]
Thank you, works like a charm!
