### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by ivanjaros** [stephenafamo/goldmark-pdf#3]
The examples listed here are not working. The link color does not accept string and the fonts are constantly throwing missing errors.

**Comment by stephenafamo** [comment]
I should update the `README.md`. LinkColor takes a [color.Color](https://pkg.go.dev/image/color#Color).

What errors are you getting regarding fonts?

**Comment by ivanjaros** [comment]
it were not found errors for various fonts. like if there was arial front used and i set the body font and pointed arial to one of the built-in fonts it did not take. also with multiple fonts i setting multiple font family values did not work.

**Comment by erwin** [comment]
Seems to work great for me! Takes about 1.2 seconds.

I tested it on VoidLinux (rolling release like Arch, but always on stable/releases).

Might be nice to directly include an example in an `./examples` folder that people can just directly run it.

Trying to do the minimum change to get your README.md example working though, I got:

```go
package main

import (
	"bytes"
	"context"
	"os"
  "image/color"
  _ "embed"

	pdf "github.com/stephenafamo/goldmark-pdf"
	"github.com/yuin/goldmark"
)

//go:embed README.md
var source []byte

func main() {
  markdown := goldmark.New(
      goldmark.WithRenderer(
          pdf.New(
              pdf.WithTraceWriter(os.Stdout),
              pdf.WithContext(context.Background()),
              pdf.WithImageFS(os.DirFS(".")),
              pdf.WithLinkColor(color.RGBA{204, 69, 120, 255}),
              pdf.WithHeadingFont(pdf.GetTextFont("IBM Plex Serif", pdf.FontLora)),
              pdf.WithBodyFont(pdf.GetTextFont("Open Sans", pdf.FontRoboto)),
              pdf.WithCodeFont(pdf.GetCodeFont("Inconsolata", pdf.FontRobotoMono)),
          ),
      ),
  )
  
  var buf bytes.Buffer
  if err := markdown.Convert(source, &buf); err != nil {
    panic(err)
  }


  if err := os.WriteFile("README.pdf", buf.Bytes(), 0644); err != nil {
    panic(err)
  }
}
```

For reference, here's the PDF it makes for me from (from the goldmark-pdf/README.md)

Thanks so much for this!

[README.pdf](https://github.com/stephenafamo/goldmark-pdf/files/10082356/README.pdf)

**Comment by ivanjaros** [comment]
> Seems to work great for me! Takes about 1.2 seconds.

`panic: could not load fonts: could not get font bytes. IBM Plex Serif-regular: Unknown font`

If i comment out fonts altogether I get
`panic: could not load fonts: could not get font bytes. Roboto-regular: Unknown font`

My testing code is this reference page https://github.com/fullpipe/markdown-test-page/edit/master/test-page.md

**Comment by ivanjaros** [comment]
I seems the problem comes from here github.com/go-swiss/font/google/google.go:51:GetFontBytes() where it tries to downlaod fronts from google fonts but fails. I have disabled my firewall but it did not help. So it looks like the font config is no longer valid or google fonts do not serve the proper format or on different urls.

**Comment by ivanjaros** [comment]
This fails. Even though the json definition for the font exists.
![obrázok](https://user-images.githubusercontent.com/64546059/208235583-674da91f-fab4-4c18-ad19-5eadd701cf92.png)

**Comment by ivanjaros** [comment]
When I use on of the built-in fonts, like FontCourier, the problem is gone. I am not sure if the problem is with the go-swiss/fonts library or this one(all code looks fine, i see no bugs anywhere) but there is a problem nevertheless.

**Comment by stephenafamo** [comment]
I could not replicate the error you're getting.

I have updated both the fonts package and regenerated the font definitions just in case.

**Comment by ivanjaros** [comment]
I have created new directory, in it i have put md file with content i linked above and main.go with content by erwin above and built it and run it and got `panic: could not load fonts: could not get font bytes. IBM Plex Serif-regular: Unknown font`.

Running go get -u, just in case, did not help.

**Comment by stephenafamo** [comment]
I did the same:

Code:

```go
package main

import (
	"context"
	_ "embed"
	"image/color"
	"os"

	pdf "github.com/stephenafamo/goldmark-pdf"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

//go:embed page.md
var markdown []byte

func main() {
	file, err := os.Create("./test/output.pdf")
	if err != nil {
		panic(err)
	}

	md := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithRenderer(
			pdf.New(
				pdf.WithTraceWriter(os.Stdout),
				pdf.WithContext(context.Background()),
				pdf.WithImageFS(os.DirFS(".")),
				pdf.WithLinkColor(color.RGBA{204, 69, 120, 255}),
				pdf.WithHeadingFont(pdf.GetTextFont("IBM Plex Serif", pdf.FontLora)),
				pdf.WithBodyFont(pdf.GetTextFont("Open Sans", pdf.FontRoboto)),
				pdf.WithCodeFont(pdf.GetCodeFont("Inconsolata", pdf.FontRobotoMono)),
			),
		),
	)

	if err := md.Convert(markdown, file); err != nil {
		panic(err)
	}
}
```

Expectedly, I got some errors with the images:

```sh
❯ go run ./test
2022/12/19 11:59:02 IMAGE ERROR: open http://placekitten.com/1280/800: invalid argument
2022/12/19 11:59:02 IMAGE ERROR: open http://placekitten.com/480/400: invalid argument
2022/12/19 11:59:02 IMAGE ERROR: open https://img.youtube.com/vi/s6bCmZmy9aQ/0.jpg: invalid argument
```

Generated PDF: [output.pdf](https://github.com/stephenafamo/goldmark-pdf/files/10258647/output.pdf)

**Comment by ivanjaros** [comment]
Try https://github.com/ivanjaros/pdftest

**Comment by stephenafamo** [comment]
Didn't import `GFM` so the tables didn't render correctly, but the rest did

[test.pdf](https://github.com/stephenafamo/goldmark-pdf/files/10258941/test.pdf)

**Comment by ivanjaros** [comment]
What OS are you on? I am on Windows so maybe there is issue with OS-specific paths?

**Comment by ivanjaros** [comment]
ok, it is a problem of the aforementioned go-swiss library, not this one, because even its example is not working.

**Comment by stephenafamo** [comment]
I'm on MacOS, so that may explain it.

**Comment by ivanjaros** [comment]
I found the bug. hopefully the go-swiss author will fix it soon.

**Comment by stephenafamo** [comment]
I hate to break it to you.... but I'm the `go-swiss` author 😂

**Comment by stephenafamo** [comment]
I've made a fix on the fonts package, tagged a new release and updated goldmark-pdf to use the latest version of the fonts package.

Try again and let me know.

**Comment by ivanjaros** [comment]
> I've made a fix on the fonts package, tagged a new release and updated goldmark-pdf to use the latest version of the fonts package.
> 
> Try again and let me know.

**It is working now.** But i see two problems that are not related to this so I don't want to pollute this issue any more but
a) a small image is being stretched for the entire width of the pdf document instead of preserving its size. I think this needs some kind of dpi conversion to get relatively acceptable dimensions? but what is relative, right?

and
b) local links/navigation are not working. So like with the testing MD i linked above, you have table of contents and headers have "name" attribute for navigation, but they are ignored in PDF and only empty links are rendered.

oh, and c) image's alt text is being rendered as well even if the image is present.

**Comment by stephenafamo** [comment]
Thank you so much.

Kindly create individual issues for those and we can take a look at them individually.
